### model
model_name_or_path: /n/home07/than157/desktop/done-large_projects/learn-better/evolm/pretrain/lit-trainer/models/pretrained/llama-0.5B-10BT-weightdecay0.1-seed42/final-hf

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: config_hub/official_configs/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: metamathqa
template: default
cutoff_len: 2048
max_samples: 1000000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: llamafactory_out/llama-0.5B-10BT-weightdecay0.1-seed42-metamathqa
logging_steps: 10
save_steps: 1000
plot_loss: false
overwrite_output_dir: true

### train
# 4 * 32 * 1 GPU = 128 | 4 * 16 * 2 GPU = 128 | 4 * 8 * 4 GPU = 128 | 4 * 4 * 8 GPU = 128
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
do_eval: false

### wandb
report_to: wandb
run_name: llama-0.5B-10BT-weightdecay0.1-seed42-metamathqa

