export WANDB_API_KEY=4d037a62ff4fafda28bf95535a019f6a0c2a1b41
export WANDB_ENTITY=zhenting-ml
export WANDB_PROJECT=overtraining

data_src_dir="./data/gsm8k"
project_name="overtraining"
run_name="verl_demo"
model_path="Qwen/Qwen2.5-0.5B-Instruct"

PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
    data.train_files=${data_src_dir}/train.parquet \
    data.val_files=${data_src_dir}/test.parquet \
    data.train_batch_size=256 \
    data.max_prompt_length=512 \
    data.max_response_length=256 \
    actor_rollout_ref.model.path=$model_path \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
    critic.optim.lr=1e-5 \
    critic.model.path=$model_path \
    critic.ppo_micro_batch_size_per_gpu=4 \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.logger=['console','wandb'] \
    trainer.project_name=$project_name \
    trainer.experiment_name=$run_name \
    trainer.val_before_train=False \
    trainer.default_hdfs_dir=null \
    trainer.n_gpus_per_node=1 \
    trainer.nnodes=1 \
    trainer.save_freq=20 \
    trainer.test_freq=5 \
    trainer.total_epochs=15 2>&1 | tee logs/${run_name}.log
